name: minus_app
description: A new flutter project.
dependencies:
  flutter:
    path: ../../fork/flutter/packages/flutter
  flutter_test:
    path: ../../fork/flutter/packages/flutter_test
  flutter_driver:
    path: ../../fork/flutter/packages/flutter_driver
  firebase:
    git: "git@github.com:flutter/firebase-dart.git"
