name: plus_app
description: A plus flutter project.
dependencies:
  flutter:
    path: ../../../vanadium/release/projects/baku/deps/flutter/packages/flutter
  flutter_test:
    path: ../../../vanadium/release/projects/baku/deps/flutter/packages/flutter_test
  flutter_driver:
    path: ../../../vanadium/release/projects/baku/deps/flutter/packages/flutter_driver
  firebase:
    path: ../../fork/flutterfire
